apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml

namespace: trem

images:
- name: trem-giz-api
  newName: cesarapires/trem-giz
  newTag: a397c766d799a15c898f76ca74303d0d475f41a4
