apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml

namespace: trem

images:
- name: trem-giz-api
  newName: cesarapires/trem-giz
  newTag: 7ff9784407f7e6c12edaeb6e581b7b31e3885fdc
