apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: trem

images:
- name: trem-giz-api
  newName: cesarapires/trem-giz
  newTag: d95f1b3f8f404bb2ec32447494d9a64ea2c0dc2f
