apiVersion: v1
kind: Service
metadata:
  name: trem-giz-api
  labels:
    app: trem-giz-api
spec:
  selector:
    app: trem-giz-api
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
