apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: trem
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017